### ISSUE TITLE
add key combinations & clarify grammar

### ISSUE THREAD

**Issue by delanym** [syscolabs/kasaya#14]
I want to press key combinations like:
```
press shift tab
press ctrl a
```

Would be good to clarify grammar too. I'd expect this to enter the password without quotes: 
`type 'mypassword'`

You might want to treat spaces as argument delimiters. So if my password had a space, it should be wrapped in quotes.

**Comment by randilu** [comment]
@delanym 
You should wrap the argument/s with double quotes if it **contains spaces**.(mandatory)

1. So in your case in order to provide a key combination, the syntax would be
- To press _shift_ key and _tab_ key together
```press "shift+tab"```

- To press _ctrl_ key and _a_ key together
```press "control+a"```

(Note that in here keys combinations should be provided in lower case without spaces)

2. If you want to type texts with spaces, the syntax would be `type "sample text with spaces"`. In your case the command would be `type mypassword` or `type "mypassword"`
